# Generated by Django 5.0.3 on 2024-04-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_person_remove_photo_album_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='profession',
            new_name='country',
        ),
    ]
